#!/usr/bin/env python3

import os
import sys
import timeit

for directory, _, files in sorted(os.walk(sys.argv[1])):
    if 'solve.py' in files:
        print('---', f'{directory}')

        if 'input.txt' in files:
            cmd = f'cat {directory}/input.txt | python3 {directory}/solve.py'
        else:
            cmd = f'python3 {directory}/solve.py'

        start = timeit.default_timer()
        os.system(cmd)
        elapsed = round(timeit.default_timer() - start, 3)
        print('---', 'Time:', elapsed, end='\n\n')
